"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { Zap, Shield, Clock, BarChart3, Sparkles, ArrowRight, Check, Pin } from "lucide-react";

const features = [
  { icon: Sparkles, title: "AI Content Engine", desc: "Title, description, hashtags — all generated by AI from a single image upload. Gemini, OpenAI, DeepSeek supported.", color: "text-accent-fuchsia" },
  { icon: Clock, title: "Smart Scheduling", desc: "Human-like randomized delays (15-60 min) between posts. Daily cap enforced. Pinterest TOS respected.", color: "text-accent-cyan" },
  { icon: Shield, title: "Official API Only", desc: "Zero scraping. Zero bots. Only Pinterest API v5 with OAuth2. Your account stays safe.", color: "text-accent-green" },
  { icon: BarChart3, title: "Analytics Dashboard", desc: "Track posts, success rates, and daily activity across all your connected Pinterest accounts.", color: "text-accent-gold" },
];

const plans = [
  { name: "Free", price: "$0", features: ["1 Pinterest account", "5 pins/day", "Gemini AI", "Queue management", "Basic analytics"], cta: "Get started", highlight: false },
  { name: "Pro", price: "$19", features: ["Unlimited accounts", "15 pins/day per account", "All AI providers", "Bulk upload", "Full analytics", "Priority support"], cta: "Start free trial", highlight: true },
  { name: "Agency", price: "$49", features: ["Everything in Pro", "Team members", "Client accounts", "API access", "White-label ready", "Custom limits"], cta: "Contact sales", highlight: false },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-bg overflow-hidden">
      {/* Navbar */}
      <nav className="fixed top-0 w-full z-50 border-b border-border/50" style={{ background: "rgba(7,7,18,0.8)", backdropFilter: "blur(20px)" }}>
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: "linear-gradient(135deg, #7c3aed, #e879f9)" }}>
              <Pin size={16} className="text-white" />
            </div>
            <span className="font-display font-bold text-xl text-white">PinForge <span className="text-primary-light">AI</span></span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm text-text-muted">
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
            <a href="#how" className="hover:text-white transition-colors">How it works</a>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/auth/login" className="btn-ghost text-sm">Log in</Link>
            <Link href="/auth/signup" className="btn-primary text-sm">Get started</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative pt-32 pb-24 px-6 flex flex-col items-center text-center">
        <div className="hero-blob-1" />
        <div className="hero-blob-2" />

        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="relative z-10 max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-primary/30 bg-primary/10 text-primary-light text-sm font-body mb-8">
            <Sparkles size={14} />
            <span>AI-powered Pinterest automation — 100% official API</span>
          </div>

          <h1 className="font-display text-5xl md:text-7xl font-bold text-white leading-[1.1] mb-6">
            Pin smarter,<br />
            <span style={{ backgroundImage: "linear-gradient(135deg, #9333ea, #e879f9, #f59e0b)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              grow faster
            </span>
          </h1>

          <p className="font-body text-xl text-text-muted max-w-2xl mx-auto mb-10 leading-relaxed">
            Upload your product images, let AI write the perfect titles, descriptions, and hashtags — then schedule them to post automatically. 
            No bots. No scraping. Just real results.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/auth/signup" className="btn-primary flex items-center gap-2 justify-center text-base">
              Start automating free <ArrowRight size={18} />
            </Link>
            <Link href="#how" className="btn-ghost flex items-center gap-2 justify-center text-base">
              See how it works
            </Link>
          </div>

          <p className="text-text-dim text-sm mt-6">No credit card required · Free forever plan available</p>
        </motion.div>

        {/* Dashboard preview card */}
        <motion.div
          initial={{ opacity: 0, y: 60 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.9, delay: 0.3 }}
          className="relative z-10 mt-20 w-full max-w-5xl"
        >
          <div className="gradient-border p-1">
            <div className="rounded-[14px] bg-bg-surface overflow-hidden" style={{ boxShadow: "0 40px 80px rgba(0,0,0,0.6)" }}>
              {/* Mock dashboard preview */}
              <div className="flex h-[380px]">
                {/* Sidebar mock */}
                <div className="w-56 bg-bg border-r border-border/50 p-4 flex flex-col gap-2">
                  <div className="flex items-center gap-2 mb-4 px-2">
                    <div className="w-6 h-6 rounded bg-primary/30" />
                    <div className="h-3 w-24 rounded bg-border" />
                  </div>
                  {["Dashboard", "Create Pins", "Queue", "Analytics", "Accounts"].map((label, i) => (
                    <div key={label} className={`flex items-center gap-3 px-3 py-2 rounded-lg ${i === 1 ? "bg-primary/20 border border-primary/30" : ""}`}>
                      <div className={`w-4 h-4 rounded-sm ${i === 1 ? "bg-primary-light" : "bg-border"}`} />
                      <span className={`text-xs font-body ${i === 1 ? "text-primary-light" : "text-text-dim"}`}>{label}</span>
                    </div>
                  ))}
                </div>
                {/* Main mock */}
                <div className="flex-1 p-6">
                  <div className="grid grid-cols-4 gap-3 mb-6">
                    {[
                      { label: "Posted Today", val: "12", color: "#9333ea" },
                      { label: "Queued", val: "28", color: "#e879f9" },
                      { label: "This Week", val: "74", color: "#06b6d4" },
                      { label: "Success Rate", val: "98%", color: "#10b981" },
                    ].map(({ label, val, color }) => (
                      <div key={label} className="glass-card p-3">
                        <div className="text-xs text-text-dim font-body mb-1">{label}</div>
                        <div className="font-display font-bold text-2xl" style={{ color }}>{val}</div>
                      </div>
                    ))}
                  </div>
                  {/* Pin cards mock */}
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { status: "posted", h: "h-20", color: "#10b981" },
                      { status: "scheduled", h: "h-28", color: "#9333ea" },
                      { status: "posted", h: "h-24", color: "#10b981" },
                    ].map(({ status, h, color }, i) => (
                      <div key={i} className="glass-card p-3">
                        <div className={`${h} rounded-lg mb-2`} style={{ background: `linear-gradient(135deg, rgba(147,51,234,0.2), rgba(232,121,249,0.1))` }} />
                        <div className="h-2 w-3/4 rounded bg-border mb-1" />
                        <div className="h-2 w-1/2 rounded bg-border/50 mb-2" />
                        <div className="inline-flex px-2 py-0.5 rounded-full text-[10px]" style={{ background: `${color}20`, color, border: `1px solid ${color}30` }}>
                          {status}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="font-display text-4xl font-bold text-white mb-4">Everything you need to scale on Pinterest</h2>
            <p className="text-text-muted text-lg">Built for creators, affiliate marketers, and e-commerce brands.</p>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            {features.map(({ icon: Icon, title, desc, color }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                className="glass-card p-6 group hover:border-primary/40 transition-all duration-300"
              >
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center mb-4 ${color.replace("text-", "bg-").replace("accent-", "accent-")}/10 border border-current/20`} style={{ background: "rgba(147,51,234,0.1)" }}>
                  <Icon className={color} size={24} />
                </div>
                <h3 className="font-display text-xl font-semibold text-white mb-2">{title}</h3>
                <p className="text-text-muted font-body leading-relaxed">{desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="py-24 px-6 border-t border-border/30">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="font-display text-4xl font-bold text-white mb-4">Up and running in 5 minutes</h2>
          <p className="text-text-muted text-lg mb-16">Connect your Pinterest account, upload images, let AI do the rest.</p>
          <div className="flex flex-col md:flex-row gap-0">
            {[
              { step: "01", title: "Connect Pinterest", desc: "Click connect, authorize with your Pinterest account via official OAuth2.", color: "#9333ea" },
              { step: "02", title: "Upload & Describe", desc: "Upload your product images and give a quick product description.", color: "#e879f9" },
              { step: "03", title: "AI Writes Content", desc: "AI generates SEO-optimized title, description, hashtags, and alt text.", color: "#f59e0b" },
              { step: "04", title: "Auto-posts Safely", desc: "Scheduler posts with human-like delays. Daily cap respected. You stay safe.", color: "#06b6d4" },
            ].map(({ step, title, desc, color }, i) => (
              <div key={step} className="flex-1 flex flex-col items-center p-6 relative">
                {i < 3 && <div className="hidden md:block absolute right-0 top-8 w-1/2 h-px border-t border-dashed border-border" />}
                <div className="w-14 h-14 rounded-2xl flex items-center justify-center font-display font-bold text-xl mb-4" style={{ background: `${color}20`, color, border: `1px solid ${color}40` }}>
                  {step}
                </div>
                <h3 className="font-display font-semibold text-white mb-2">{title}</h3>
                <p className="text-text-muted text-sm text-center font-body">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 px-6 border-t border-border/30">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="font-display text-4xl font-bold text-white mb-4">Simple, honest pricing</h2>
            <p className="text-text-muted text-lg">Start free. Scale when you're ready.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {plans.map(({ name, price, features, cta, highlight }) => (
              <div key={name} className={`relative rounded-2xl p-6 ${highlight ? "gradient-border" : "glass-card"}`} style={highlight ? { background: "linear-gradient(135deg, rgba(13,13,31,0.95), rgba(22,22,48,0.9))" } : {}}>
                {highlight && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 rounded-full text-xs font-display font-semibold text-white" style={{ background: "linear-gradient(135deg, #7c3aed, #e879f9)" }}>
                    Most popular
                  </div>
                )}
                <h3 className="font-display text-xl font-bold text-white mb-1">{name}</h3>
                <div className="font-display text-4xl font-bold mb-1" style={{ color: highlight ? "#a855f7" : "#f8fafc" }}>
                  {price}<span className="text-base text-text-muted font-body">/mo</span>
                </div>
                <div className="h-px bg-border my-4" />
                <ul className="space-y-3 mb-6">
                  {features.map(f => (
                    <li key={f} className="flex items-center gap-3 text-sm font-body text-text-muted">
                      <Check size={14} className="text-accent-green flex-shrink-0" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Link href="/auth/signup" className={`block text-center py-3 rounded-xl font-display font-semibold text-sm transition-all duration-200 ${highlight ? "btn-primary" : "btn-ghost"}`}>
                  {cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/30 py-12 px-6">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: "linear-gradient(135deg, #7c3aed, #e879f9)" }}>
              <Pin size={14} className="text-white" />
            </div>
            <span className="font-display font-bold text-white">PinForge AI</span>
          </div>
          <p className="text-text-dim text-sm font-body">Official Pinterest API v5 only · No scraping · No bots</p>
          <p className="text-text-dim text-sm font-body">© 2024 PinForge AI</p>
        </div>
      </footer>
    </div>
  );
}
